<?php
/**
 * Created by PhpStorm.
 * User: Christopher
 * Date: 22.10.2017
 * Time: 18:28
 */
namespace Album\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;
class AlbumController extends AbstractActionController
{
    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

    public function addAction()
    {

    }

    public function editAction()
    {

    }
    public function deleteAction()
    {

    }
}